### ISSUE TITLE
Corner radius for LFGlassView

### ISSUE THREAD

**Issue by rounak** [evadne/LiveFrost#12]
Any reason why you give a cornerRadius to LFGlassView?

**Comment by ghost** [comment]
@evadne ?

We could remove it from the defaults, if desired. I'm not sure exactly why it's there, myself.

**Comment by ghost** [comment]
...of course, there are probably a number of people who are already expecting this object to work with this default in their codebases, right now. Hmm. Probably not such a good idea to remove it, then.

If I had to speculate what the reason was, it might have been "it looks nice". But don't take that as the final word.

**Comment by evadne** [comment]
The corner radius is applied to the view for arbitrary, cosmetic reasons:

https://github.com/radi/LiveFrost/blob/develop/LiveFrost/LFGlassView.m#L50

**Comment by ArtFeel** [comment]
I think it's better to remove `cornerRadius` from defaults and move it into sample view controller. You can update pod version for `1.1.0` to not brake expected behavior.

**Comment by ghost** [comment]
Okay, that sounds alright.

We can tag the upcoming version `1.0.5`, and then `1.1.0` will be this coming version, plus the defaults change. Unless there are any further objections.

**Comment by evadne** [comment]
Agreed.

**Comment by ghost** [comment]
I'm afraid that I don't have commit access to the sample project, so I can't make the change to add cornerRadius to that project.

However, `cornerRadius` has been removed from develop, and I'll most likely tag that as `1.1.0` later tomorrow.

**Comment by evadne** [comment]
You should have commit access to https://github.com/radi/LiveFrost-Sample. Smite me otherwise.

**Comment by ghost** [comment]
There we go, thanks.

**Comment by ghost** [comment]
Done and done.
