### ISSUE TITLE
Here's what I found on the iPad (non-retina) simulator

### ISSUE THREAD

**Issue by kukosk** [evadne/LiveFrost#14]
<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaPremultipliedLast; 447 bytes/row.
<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaPremultipliedLast; 447 bytes/row.
<Error>: CGContextConcatCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
<Error>: CGContextScaleCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

If you need some more info just let me know.

**Comment by evadne** [comment]
Thanks, could you please post your Xcode version, and the iOS version you
are running in the simulator, and possibly the model of your Mac?

On Feb 1, 2014, at 3:13, "Jakub Kleň" notifications@github.com wrote:

: CGBitmapContextCreate: unsupported parameter combination: 8 integer
bits/component; 32 bits/pixel; 3-component color space;
kCGImageAlphaPremultipliedLast; 447 bytes/row.
: CGBitmapContextCreate: unsupported parameter combination: 8 integer
bits/component; 32 bits/pixel; 3-component color space;
kCGImageAlphaPremultipliedLast; 447 bytes/row.
: CGContextConcatCTM: invalid context 0x0. This is a serious error. This
application, or a library it uses, is using an invalid context and is
thereby contributing to an overall degradation of system stability and
reliability. This notice is a courtesy: please fix this problem. It will
become a fatal error in an upcoming update.
: CGContextScaleCTM: invalid context 0x0. This is a serious error. This
application, or a library it uses, is using an invalid context and is
thereby contributing to an overall degradation of system stability and
reliability. This notice is a courtesy: please fix this problem. It will
become a fatal error in an upcoming update.

If you need some more info just let me know.

—
Reply to this email directly or view it on
GitHubhttps://github.com/radi/LiveFrost/issues/14
.

**Comment by ghost** [comment]
I can tell you what the output's saying. The target bitmaps that we're trying to create for the blurred view based on scaled `CGRect` the `LFGlassView` generated are somehow not valid, in this case. Hard to say why that is without seeing the code that uses this object.

I have no idea what that scaled `CGRect` looks like from this console output alone. It's stored in a local variable called `bufferSize`, not to be confused with the ivar `bufferSize`.

Could you print that information out using `NSStringFromCGRect(...)` and `NSLog(...)`? Around [line 229](https://github.com/radi/LiveFrost/blob/37300f39b5ec99cead9f088b207fd27f397ef565/LiveFrost/LFGlassView.m#L229) would be preferred, just before `CGBitmapContextCreate` is called in `-recreateImageBuffers`.

Be sure that it's `bufferSize` and not `_bufferSize` or `self.bufferSize`, so you get the local variable and NOT the instance variable. (Who named that local variable, anyway? Might have been me. Sorry about that.)

Best thing of all would be to have a test case with sample code for us to look at, but I think this information would be a great start. Besides the usual "what platform are you on, etc..." bits.

**Comment by ghost** [comment]
Sorry, you want `NSStringFromCGSize(...)`, not `CGRect`. These are `CGSize` structures. My bad.

**Comment by kukosk** [comment]
Hi,

XCode Version 5.0.2 (5A3005)
Targeting for iOS 6.0 SDK, Base SDK 7.0
In the simulator, I'm running 7.0
My mac is MacBook Pro 15-inch, Mid 2010 with 2.4GHz Intel Core i5, OSX 10.9.1 (13B42)

About the bufferSize var. I put an NSLog in there, and it got called 3 times, displaying the first error after the 3rd time:
{80, 11}
{80, 11.75}
{111.75, 11.75}

The blur is displayed in the right vc of my custom split view controller container. When the view is loaded, it's size is {320.0, 47.0}, and gets resizes for iPad to {447.0, 47.0}. I'm also seeing those errors when rotating. Hope this helps :)

**Comment by ghost** [comment]
Alright, give the develop branch at https://github.com/radi/LiveFrost/commit/6ba5dabbb86f6d62cfe4b3103f48647ba6b4b654 a try.

**Comment by kukosk** [comment]
Yes, that fixes it, thank you a lot! :)
